export * as menü from "./menü"
export * as ping from "./ping"
export * as plus from "./plus"
export * as prophezei from "./prophezei"
export * as rangliste from "./rangliste"
export * as stats from "./stats"
export * as wann from "./wann"
export * as heute from "./heute"